# List of servers to monitor
servers:
  - name: "Web Server 01"
    host: "18.60.39.71"
    port: 22
    user: "ec2-user"
  # - name: "DB Server"
  #   host: "192.168.1.11"
  #   port: 22
  #   user: "your_user"
  # Add more servers here

# SMTP settings for sending email reports
smtp:
  host: "smtp.gmail.com" # Use your SMTP server
  port: 587
  username: "nani.y9966@gmail.com" # Use your email address
  password: "sfjwjzerlgbegogf" # For app passwords, use them here
  from: "nani.y9966@gmail.com"
  to:
    - "prabhakararao.nandigrama@assettl.com"
    # - "recipient2@example.com"

# The private key for SSH authentication
# Use an absolute path or a path relative to the executable
ssh_key_path: "/tmp/HYD.pem"