# List of servers to monitor
servers:
  # This server uses an SSH key for authentication
  - name: "Web Server 01 (Key Auth)"
    host: "1.1.1.1"
    port: 22
    user: "root" # Replace with your username for this server
    key_path: "/path/to/pem" # Specify the key path for this server

  # This server uses a password for authentication
  - name: "DB Server (Password Auth)"
    host: "192.168.1.11" # Replace with your server's IP
    port: 22
    user: "your_db_user" # Replace with your username for this server
    password: "Your_DB_Server_Password123" # Specify the password for this server

  # You can add more servers, each with either a key_path or a password.
  - name: "Staging Server (Password Auth)"
    host: "192.168.1.12"
    port: 22
    user: "staging_user"
    password: "AnotherPassword"

# SMTP settings for sending email reports
smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "example@gmail.com" # Replace with your Gmail address
  password: "your-google-app-password" # Make sure this is your app password
  from: "example@gmail.com" # Replace with your Gmail address
  to:
    - "example@gmail.com" # Replace with the email address to receive reports

# The global ssh_key_path is no longer used and can be deleted from this file.